### ISSUE TITLE
Missing 'off' button (enable ECO?)

### ISSUE THREAD

**Issue by freddieleeman** [cyberjunky/home-assistant-toon_climate#23]
I like the new 'auto' feature, but removing the option to turn it 'off' messed up my automations. Would it be an option to add the 'off'-button again and make it enable the ECO mode?

Also the service 'climate.turn_on' and 'climate.turn_off' could switch to 'auto' and 'eco'-mode for instance.

**Comment by rbak69** [comment]
@freddieleeman sorry about messing up your automations but the Toon cannot really be switched "off" hence why I changed the code to use "heat" and "auto" to reflect the actual behaviour of the Toon.

The service 'climate.turn_on' and 'climate.turn_off' are standard home assistant functions to turn climate devices on and off. In this case you cannot turn the Toon device "off"  as it basically only consists off a "manual" and and "schedule" mode. You can even consider the vacation mode in the Toon as a sort ot manual mode. Although the Toon itself does also allow you to set an end date which we are unable to do with the web requests as far as I am aware. I suggest you use the service "climate.set_hvac_mode" instead to switch the Toon between "manual" and "schedule"mode. 

See below the example of two scripts that can set the Toon to "manual" or "scheduled" mode 

```yaml
script:
  toon_enable_manual_mode:
    alias: Toon enable Manual mode
    sequence:
    - service: climate.set_hvac_mode
      data:
        hvac_mode: 'heat'
      entity_id: climate.thermostaat
    mode: single
  toon_enable_schedule_mode:
    alias: Toon enable schedule mode
    sequence:
    - service: climate.set_hvac_mode
      data:
        hvac_mode: 'auto'
      entity_id: climate.thermostaat
    mode: single
```

If you wish to use the "eco/vacation" preset you can do so by using the service "climate.set_preset_mode". See below the example of a script that can set the Toon to the "eco" preset.

```yaml
script:    
  toon_activate_preset_eco:
    alias: Toon activate preset Eco
    sequence:
    - service: climate.set_preset_mode
      data:
        preset_mode: 'eco'
      entity_id: climate.thermostaat
    mode: single
```
Obviously you can do the same for any of the other standard presets for the Toon. The latter can be called in either the "manual" or "schedule" operation mode of the Toon.

See the example scripts below:

```yaml
script:
  toon_activate_preset_comfort:
    alias: Toon activate preset Comfort
    sequence:
    - service: climate.set_preset_mode
      data:
        preset_mode: comfort
      entity_id: climate.thermostaat
    mode: single
  toon_activate_preset_away:
    alias: Toon activate preset Away
    sequence:
    - service: climate.set_preset_mode
      data:
        preset_mode: away
      entity_id: climate.thermostaat
    mode: single
  toon_activate_preset_home:
    alias: Toon activate preset Home
    sequence:
    - service: climate.set_preset_mode
      data:
        preset_mode: home
      entity_id: climate.thermostaat
    mode: single
  toon_activate_preset_sleep:
    alias: Toon activate preset Sleep
    sequence:
    - service: climate.set_preset_mode
      data:
        preset_mode: sleep
      entity_id: climate.thermostaat
    mode: single
 ```  

I hope that will resolve your automation issues.
