### ISSUE TITLE
Get current temperature setting

### ISSUE THREAD

**Issue by GertJanArts** [cyberjunky/home-assistant-toon_climate#34]
Hi,
Is it possible to add the current temperature setting as an entity?
That way i can use the integration manual
Thanks

**Comment by cyberjunky** [comment]
You can always use a template sensor to create one?
```
- platform: template
    sensors:
      temperatuur_woonkamer:
        friendly_name: "Temperatuur Woonkamer"
        value_template: "{{ state_attr('climate.toon','current_temperature') }}"
        unit_of_measurement: °C

```

**Comment by GertJanArts** [comment]
ok, that's works but that's not what I mean.
I am looking for a way to get the temperature setting from Toon and not the current temperature.
Thanks

**Comment by cyberjunky** [comment]
@GertJanArts this is basic home-assistant skill/stuff, every attribute can be put in a sensor, so here you go:
```
- platform: template
    sensors:
      temperatuur_set:
        friendly_name: "Temperatuur Set"
        value_template: "{{ state_attr('climate.toon','temperature') }}"
        unit_of_measurement: °C
```
