### ISSUE TITLE
Please add max_temp as a user configurable variable

### ISSUE THREAD

**Issue by Ysbrand** [cyberjunky/home-assistant-toon_climate#4]
Hi Ron,

I tried to use max_temp in my configuration, but it seems that HA is not too excited about that. For now, I've just hardcoded DEFAULT_MAX_TEMP = 22.0 but it will be nice if this can be configured (there might be other properties as well (documented in https://developers.home-assistant.io/docs/entity_climate/)

**Comment by cyberjunky** [comment]
Yes I will add max/min temp soon, and also fix some other minor stuff.

**Comment by cyberjunky** [comment]
@ysbrand Can you try version 1.0.6 I added min/max temp settings.

**Comment by Ysbrand** [comment]
@cyberjunky : Works like a charm:
```
climate:
  - platform: toon_climate
    name: Toon Thermostaat
    host: !secret toon_ip
    port: !secret toon_port
    scan_interval: 60
    min_temp: 12
    max_temp: 22
```
```
`hvac_modes: heat, off
min_temp: 12
max_temp: 22
preset_modes: away, comfort, home, sleep
current_temperature: 19.3
temperature: 20
hvac_action: off
preset_mode: null
burner_info: 0
modulation_level: 0
friendly_name: Toon Thermostaat
supported_features: 17
```

Note:
Before using the new settings, first restart HA with the new version of the integration.
