### ISSUE TITLE
Entity not visible in HA

### ISSUE THREAD

**Issue by DennisDeKoster** [cyberjunky/home-assistant-toon_climate#45]
Hi there, my apologies if I missed something. But I installed toon_climate through HACS and added the configuration in the yaml file. But I cannot find the climate.toon_climate entity anywhere. I restarted/rebooted many times. What am I doing wrong here?

```
climate:
  #Rpi Fan control
  - platform: generic_thermostat
    name: Raspberry Pi
    heater: switch.rpi_ventilator
    target_sensor: sensor.processor_temperature
    min_temp: 20
    max_temp: 50
    ac_mode: true
    target_temp: 40
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    initial_hvac_mode: "cool"
    precision: 0.5
  # Rooted Toon
  - platform: toon_climate
    name: Toon Thermostaat
    host: 10.21.8.104
    port: 80
    scan_interval: 30
    min_temp: 6.0
    max_temp: 30.0
```
