### ISSUE TITLE
HA Trigger not working on Burnerinfo change

### ISSUE THREAD

**Issue by Tweak-NL** [cyberjunky/home-assistant-toon_climate#47]
Hello, maybe im just doing something wrong.. But it seems i cannot make a trigger that detects when burnerinfo changes to 0 or 1 it only works if the trigger is on "When Burner info of Toon Thermostat changes" but that is not what i need.

I am trying to switch from Domoticz to HA and currently Domoticz is turning my floor heating pump on and off with the info from Burnerinfo. So im trying to build this in HA but it is not working. 

See the screenshot with the trigger that does not work.

![image](https://github.com/cyberjunky/home-assistant-toon_climate/assets/67078330/af5a3bb8-d73c-49c4-9f59-c07d7cb9ae40)

`platform: state
entity_id:
  - climate.toon_thermostat
attribute: burner_info
to: "1"
from: "0"`

**Comment by cyberjunky** [comment]
Try this, this works:
```

automation:
  - alias: "Detect Burnerstate change"
    trigger:
      platform: state
      entity_id: climate.toon_thermostat
    condition:
      condition: template
      value_template: >
        {{ trigger.from_state and
            trigger.to_state.attributes.burner_info == 0 and
            trigger.from_state.attributes.burner_info == 1}}
    action:
      service: persistent_notification.create
      data:
        message: Burner state changed!
        title: "Thermostat Info"
```
