### ISSUE TITLE
When changing temperature to a value that is also a preset some presets are not found

### ISSUE THREAD

**Issue by darkrain-nl** [cyberjunky/home-assistant-toon_climate#49]
Hi I opened https://github.com/home-assistant/core/issues/137538 today and  was told to report that here.

When I change the temperature to a value  that has a preset as well (only one preset) it fails to find the preset for Away, Comfort and Eco, only Home and Sleep work as expected.

I  am unsure what extra information to add, please let me know if this is something you can have a look at...

Thanks, kind regards,
darkrain

**Comment by darkrain-nl** [comment]
Hmm still might just be a core thing as there is https://github.com/home-assistant/core/issues/137663 now as well...

**Comment by cyberjunky** [comment]
@darkrain-nl are you able to reproduce it? What are the steps? Not sure how and what has changed in core yet.

**Comment by darkrain-nl** [comment]
Yeah I can list the steps here:

I use the "Thermostat Card" with the following config:
```
type: thermostat
entity: climate.toon_thermostat
features:
  - style: dropdown
    type: climate-preset-modes
    preset_modes:
      - away
      - home
      - comfort
      - sleep
show_current_as_primary: true
```

Then I have the following presets:
Home: 19
Away: 17
Sleep: 15
Comfort: 20
Eco: 10

Now I set the Thermostat card to temperature 17, so I adjust the slider, not use the preset dropdown.
This generates an error.
But when I set it to 15, it selects Sleep and 19 selects Home.
So only Away, Comfort and Eco fail (Eco might be logical as I didn't select that one in the preset_modes...)
